---
- name: This is my playbook
  hosts: all
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
   
  - name: httpd service start
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: installed apache2 packsge
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: apache2 services started
    service: 
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
